name: CI/CD Pipeline - Dependency Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 3 da manhã

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Atualizar dependências
        run: python update_dependencies.py

      - name: Executar testes de integração
        run: pytest tests/

      - name: Commit e Push (se os testes passarem)
        run: |
          git config --local user.email "nicollaswendel1623@gmail.com"  # Substitua com seu e-mail
          git config --local user.name "nicollaswendel"  # Substitua com seu nome
          git add requirements.txt
          git commit -m "Atualizar dependências automaticamente" || echo "Nada para commit"
          git push
        if: success()
